import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Sidebar() {
  return (
    <aside className="w-64 bg-blue-600 text-white flex flex-col h-screen p-4">
      <div className="flex items-center mb-8">
        <span className="text-2xl font-bold">Logo</span>
      </div>
      <nav className="flex-1">
        <ul className="space-y-2">
          <li className="flex items-center gap-3 p-2 rounded hover:bg-blue-700 cursor-pointer">
            {/* Icon placeholder */}
            <span className="w-5 h-5 bg-white/20 rounded" />
            <span>Expenses</span>
          </li>
          <li className="flex items-center gap-3 p-2 rounded hover:bg-blue-700 cursor-pointer">
            <span className="w-5 h-5 bg-white/20 rounded" />
            <span>Vendors</span>
          </li>
          <li className="flex items-center gap-3 p-2 rounded hover:bg-blue-700 cursor-pointer">
            <span className="w-5 h-5 bg-white/20 rounded" />
            <span>Assets</span>
          </li>
          <li className="flex items-center gap-3 p-2 rounded hover:bg-blue-700 cursor-pointer">
            <span className="w-5 h-5 bg-white/20 rounded" />
            <span>Reports</span>
          </li>
        </ul>
      </nav>
      <div className="mt-auto text-xs text-blue-100">
        <div className="mb-2">User: John Doe</div>
        <div>© 2025 Accounting System</div>
      </div>
    </aside>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1 p-8 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
